### ISSUE TITLE
Пустой pubkey если кода контракта нет knownHashes

### ISSUE THREAD

**Issue by stels-cs** [ton-connect/demo-dapp-backend#5]
https://github.com/ton-connect/demo-dapp-backend/blob/f3eec25b4973f5c4be149519548c71f1dc282be1/state_init.go#L33-L40

В 39 строке ошибка, если хеша нет в knownHashes то вернется nil, nil, потому что err == nil с 33 строки

Наверно в 39 строке должно быть так
```go
return nil, fmt.Errorf("unknown code hash")
```

**Comment by zakhar-petukhov** [comment]
Спасибо, поправили 👍
